export const GET_BID_DETAIL_DATA = 'PaymentPage/GET_BID_DETAIL_DATA';
export const SET_BID_DETAIL_DATA = 'PaymentPage/SET_BID_DETAIL_DATA';

export const SET_PAYMENT_DATA = 'PaymentPage/SET_PAYMENT_DATA';

export const GET_USER_ADDRESSES = 'PaymentPage/GET_USER_ADDRESSES';
export const SET_USER_ADDRESSES = 'PaymentPage/SET_USER_ADDRESSES';

export const GET_SHIPPING_PROVIDERS = 'PaymentPage/GET_SHIPPING_PROVIDERS';
export const SET_SHIPPING_PROVIDERS = 'PaymentPage/SET_SHIPPING_PROVIDERS';

export const GET_SHIPPING_PROVIDER_DATA = 'PaymentPage/GET_SHIPPING_PROVIDER_DATA';
export const SET_SHIPPING_PROVIDER_DATA = 'PaymentPage/SET_SHIPPING_PROVIDER_DATA';

export const GET_PAYMENT_METHODS = 'PaymentPage/GET_PAYMENT_METHODS';
export const SET_PAYMENT_METHODS = 'PaymentPage/SET_PAYMENT_METHODS';
