export const GET_PROFILE_DATA = 'Profile/GET_PROFILE_DATA';
export const SET_PROFILE_DATA = 'Profile/SET_PROFILE_DATA';

export const SAVE_PROFILE_DATA = 'Profile/SAVE_PROFILE_DATA';
export const SAVE_NEW_PASSWORD = 'Profile/SAVE_NEW_PASSWORD';

export const GET_USER_ADDRESS_DATA = 'Profile/GET_USER_ADDRESS_DATA';
export const SET_USER_ADDRESS_DATA = 'Profile/SET_USER_ADDRESS_DATA';

export const DELETE_ADDRESS_DATA = 'Profile/DELETE_ADDRESS_DATA';
